import type { Metadata } from 'next'
import { Noto_Sans_KR } from 'next/font/google'
import './globals.css'

const NotoSansKR = Noto_Sans_KR({
  variable: '--font-noto-sans',
  display: 'swap',
  style: 'normal',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${NotoSansKR.className} antialiased`}>{children}</body>
    </html>
  )
}
