export { default as ArchitectDetail } from './ArchitectDetail/ArchitectDetail'
export { default as ArchitectMain } from './ArchitectMain/ArchitectMain'
export { default as ContentDetail } from './ContentDetail'
export { default as ContentMain } from './ContentMain'
export { default as Home } from './Home'
